export const SnackMessage = {
  success: {
    updateSubmission: "Submission updated successfully.",
    createSubmission: "Submission created successfully.",
    deleteSubmission: "Submission deleted successfully.",
    assignReviewers: "Reviewers assigned successfully.",
    addUser: "User added successfully.",
    updateUser: "User updated successfully.",
    deleteUser: "User deleted successfully.",
    updateDeadline: "Deadline updated successfully.",
    addReviews: "Reviews added successfully.",
    reSubmission: "Submission resubmitted successfully.",
  },
  error: {
    fetchSubmissions: "Failed to fetch submissions.",
    createSubmission: "Failed to create submission.",
    updateSubmission: "Failed to update submission.",
    deleteSubmission: "Failed to delete submission.",
    fetchUsers: "Failed to fetch users.",
    assignReviewers: "Failed to assign reviewers.",
    addUser: "Failed to add user.",
    updateUser: "Failed to update user.",
    deleteUser: "Failed to delete user.",
    updateDeadline: "Failed to update deadline.",
    addReviews: "Failed to add reviews.",
    getReviews: "Failed to get reviews.",
    reSubmission: "Failed to resubmit submission.",
  },
  warning: {},
};
